### ISSUE TITLE
enable `ReviewNB`

### ISSUE THREAD

**Issue by yunjunz** [opera-adt/opera-notebooks#2]
@hfattahi, It will be helpful if you could enable the notebook review using `ReviewNB`. Then we could check the notebook contents in the PR in a human-readable way, similar to what we have for `nisar-solid/ATBD` (https://github.com/nisar-solid/ATBD/pull/41).

Instructions are here: https://www.reviewnb.com/.

**Comment by gmgunter** [comment]
ReviewNB is now enabled for this repository.
